import BN from 'bn.js';
import { Channel } from '../src/channel';
import { State } from '../src/state';
import assertRevert from './helpers/assert-revert';
import { CountingGame } from '../src/test-game/counting-game';
import { sign, recover } from '../src/utils';

const StateLib = artifacts.require("./State.sol");

contract('State', (_accounts) => {
  let stateLib;
  const channelNonce = 12;
  const turnNum = 15;
  // private keys are from the accounts generated by `ganache-cli -d`
  const channelType = web3.eth.accounts.privateKeyToAccount('4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d').address; // just get a valid address
  const participantA = web3.eth.accounts.privateKeyToAccount('6cbed15c793ce57650b9877cf6fa156fbef513c4e6134f022a85b1ffdd59b2a1');
  const participantB = web3.eth.accounts.privateKeyToAccount('6370fd033278c143179d81c5526140625662b8daa446c22ee2d73db3707e620c');
  const participants = [participantA.address, participantB.address];
  const resolution = [new BN(5), new BN(4)];
  const channel = new Channel(channelType, channelNonce, participants);
  const stateType = State.StateType.Game;
  const state = new State({
    channel, stateType, turnNum, resolution, stateCount: 0,
  });
  const statePacket = state.toHex();

  before(async () => {
    stateLib = await StateLib.deployed();
  });

  it("extracts the channelType", async () => {
    const result = await stateLib.channelType.call(statePacket);
    assert.equal(channelType, result);
  });

  it("extracts the channelNonce", async () => {
    const result = await stateLib.channelNonce.call(statePacket);
    assert.equal(channelNonce, result);
  });

  it("extracts the turnNum", async () => {
    const result = await stateLib.turnNum.call(statePacket);
    assert.equal(turnNum, result);
  });

  it("extracts the number of participants", async () => {
    const n = await stateLib.numberOfParticipants.call(statePacket);
    assert.equal(n, 2);
  });

  it("extracts the participants", async () => {
    const result = await stateLib.participants.call(statePacket);
    assert.deepEqual(participants, result);
  });

  it("extracts the resolution", async () => {
    const result = await stateLib.resolution.call(statePacket);
    assert.equal(resolution[0].toNumber(), result[0]);
    assert.equal(resolution[1].toNumber(), result[1]);
  });

  it("identifies the mover based on the turnNum", async () => {
    const mover = await stateLib.mover.call(statePacket);
    // our state nonce is 15, which is odd, so it should be participant[1]
    assert.equal(mover, participants[1]);
  });

  it("identifies the indexOfMover based on the turnNum", async () => {
    const index = await stateLib.indexOfMover.call(statePacket);
    // our state nonce is 15, which is odd, so it should be participant 1
    assert.equal(index, 1);
  });

  it("can calculate the channelId", async () => {
    const chainId = await stateLib.channelId.call(statePacket);
    const localId = channel.id;

    assert.equal(chainId, localId);
  });

  it("can check if a state is signed", async () => {
    // needs to be signed by 1 as it's their move
    const { r, s, v } = sign(
      state.toHex(),
      participantB.privateKey,
    );

    await stateLib.requireSignature.call(statePacket, v, r, s);
  });

  it("will revert if the wrong party signed", async () => {
    // needs to be signed by 1 as it's their move
    const { v, r, s } = sign(state.toHex(), participantA.privateKey);
  assertRevert(stateLib.requireSignature.call(statePacket, v, r, s));
  });

  it("can check if the state is fully signed", async() => {
    const { r: r0, s: s0, v: v0 } = sign(state.toHex(), participantA.privateKey);
    const { r: r1, s: s1, v: v1 } = sign(state.toHex(), participantB.privateKey);

    await stateLib.requireFullySigned.call(statePacket, [v0, v1], [r0, r1], [s0, s1]);
  });

  it("calculates the offset for the gameState", async() => {
    const offset = await stateLib.gameStateOffset.call(statePacket);

    // should be 128 + 2 * 64 + 96 = 352
    // TODO find better way to test this
    assert.equal(offset, 352);
  });

  it("can test if the gameAttributes are equal", async() => {
    const state1 = CountingGame.preFundSetupState({channel, resolution, turnNum, gameCounter: 0 });
    const state2 = CountingGame.preFundSetupState({channel, resolution, turnNum, gameCounter: 1 });

    await assertRevert(stateLib.gameAttributesEqual.call(state1.toHex(), state2.toHex()));
  });


});
