/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ParticipantId = string;
export type SigningAddress = string;
export type Destination = string;
export type Participants = Participant[];
export type Token = string;
export type Destination1 = string;
export type Amount = string;
export type AllocationItems = AllocationItem[];
export type Allocations = Allocation[];
export type AppDefinition = string;
export type AppData = string;

export interface CloseChannel {
  [k: string]: any;
}
/**
 * This interface was referenced by `CloseChannel`'s JSON-Schema
 * via the `definition` "CloseChannelResult".
 */
export interface CloseChannelResult {
  participants: Participants;
  allocations: Allocations;
  appDefinition: AppDefinition;
  appData: AppData;
  status: "proposed" | "opening" | "funding" | "running" | "closing" | "closed";
  turnNum: string;
  [k: string]: any;
}
export interface Participant {
  participantId: ParticipantId;
  signingAddress: SigningAddress;
  destination: Destination;
  [k: string]: any;
}
export interface Allocation {
  token: Token;
  allocationItems: AllocationItems;
  [k: string]: any;
}
export interface AllocationItem {
  destination: Destination1;
  amount: Amount;
  [k: string]: any;
}
/**
 * This interface was referenced by `CloseChannel`'s JSON-Schema
 * via the `definition` "CloseChannelParams".
 */
export interface CloseChannelParams {
  channelId: string;
  [k: string]: any;
}
