/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `GetAddress`'s JSON-Schema
 * via the `definition` "GetAddressResult".
 */
export type GetAddressResult = string;

export interface GetAddress {
  [k: string]: any;
}
/**
 * This interface was referenced by `GetAddress`'s JSON-Schema
 * via the `definition` "GetAddressParams".
 */
export interface GetAddressParams {
  [k: string]: any;
}
