/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A State Channel JSON RPC 2.0 notification
 */
export type Notification1 =
  | {
      [k: string]: any;
    }
  | Notification[];
export type Notification = {
  [k: string]: any;
} & {
  [k: string]: any;
} & {
  [k: string]: any;
} & {
  [k: string]: any;
};
