/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PushMessage {
  [k: string]: any;
}
/**
 * This interface was referenced by `PushMessage`'s JSON-Schema
 * via the `definition` "PushMessageResult".
 */
export interface PushMessageResult {
  success: {
    [k: string]: any;
  };
  [k: string]: any;
}
/**
 * This interface was referenced by `PushMessage`'s JSON-Schema
 * via the `definition` "PushMessageParams".
 */
export interface PushMessageParams {
  recipient: string;
  sender: string;
  data: {
    [k: string]: any;
  };
  [k: string]: any;
}
