/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ParticipantId = string;
export type SigningAddress = string;
export type Destination = string;
export type Participants = Participant[];
export type Token = string;
export type Destination1 = string;
export type Amount = string;
export type AllocationItems = AllocationItem[];
export type Allocations = Allocation[];
export type AppData = string;
export type Allocations1 = Allocation[];
export type AppData1 = string;

export interface UpdateChannel {
  [k: string]: any;
}
/**
 * This interface was referenced by `UpdateChannel`'s JSON-Schema
 * via the `definition` "UpdateChannelResult".
 */
export interface UpdateChannelResult {
  status: string;
  funding?: {
    [k: string]: any;
  }[];
  participants: Participants;
  allocations: Allocations;
  appData: AppData;
  turnNum: number;
  channelId: string;
  [k: string]: any;
}
export interface Participant {
  participantId: ParticipantId;
  signingAddress: SigningAddress;
  destination: Destination;
  [k: string]: any;
}
export interface Allocation {
  token: Token;
  allocationItems: AllocationItems;
  [k: string]: any;
}
export interface AllocationItem {
  destination: Destination1;
  amount: Amount;
  [k: string]: any;
}
/**
 * This interface was referenced by `UpdateChannel`'s JSON-Schema
 * via the `definition` "UpdateChannelParams".
 */
export interface UpdateChannelParams {
  allocations: Allocations1;
  appData: AppData1;
  channelId: string;
  [k: string]: any;
}
